### ISSUE TITLE
Warlog command outputs error

### ISSUE THREAD

**Issue by katsukixyz** [Lycoon/clashbot#2]
Providing the bot with the following command `!warlog 0 #2YCOY8P98` results in an error message even though the index is specified. The error given is as follows:
```Wrong command usage. The index must be an integer between 1 and 0.```

The same error also occurs when an index of 1 is specified.

**Comment by Lycoon** [comment]
I suppose the problem appears for clans with public warlog having at most 4 clan wars. When the warlog is public, it will check for index consistency at this line: 

https://github.com/Lycoon/clash-bot/blob/7131e66d0fcd5858fd8ee58181bcfe953c6089fd/src/main/java/com/lycoon/clashbot/commands/WarlogCommand.java#L154

As the number of total wars is less than the number of wars I display on one page (as of now 5), it just couldn't comply with the conditions in the #checkIndex() method when I'm dividing the first with the second, which would give something below 1. The issue will be fixed in next update.

Thanks for reporting!
